### ISSUE TITLE
Please change the name of this repository to 'Prompt-Engineering-Guide'

### ISSUE THREAD

**Issue by mendel5** [msoftware/Prompt-Enggeneering-Guide#1]
Hi @msoftware , Thank you for creating this repository!

The current name of this repository is `Prompt-Enggeneering-Guide`. It seems that the name is misspelled.

I would appreciate it if you could change the name of this repository to `Prompt-Engineering-Guide`. Thank you!

**Comment by msoftware** [comment]
:-) Thank you
