### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [msoftware/Prompt-Enggeneering-Guide#2]
Hi, can you add the following Github topics to this repository?
- https://github.com/topics/chatgpt
- https://github.com/topics/prompt-engineering
- https://github.com/topics/openai
- https://github.com/topics/gpt

[This article](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) explains how to do it. It's very simple.

Thanks!

**Comment by msoftware** [comment]
Thank you for the recommendation
